version: '3.4'

services:
  helloworld:
    image: ${DOCKER_REGISTRY}/aks-helloworld:${VERSION:-dev}
    build:
      context: .
      dockerfile: Services/HelloWorld/Dockerfile
  helloworldnode:
    image: ${DOCKER_REGISTRY}/aks-helloworldnode:${VERSION:-dev}
    build:
      context: .
      dockerfile: Services/HelloNode/Dockerfile